name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: '32 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set parameters
      - name: Build Docker image
        run: bash build.sh
