name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: '32 7,19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: bash build.sh

      - name: Test Docker image
        run: bash test.sh

      - name: List Docker images
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh api https://api.github.com/user/packages/container/docker-debian-bullseye-min-stage1/versions
