name: Trim

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install jq (allows Bash to work with JSON)
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: List Docker images
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh api https://api.github.com/user/packages/container/docker-debian-bullseye-min-stage1/versions
